### ISSUE TITLE
Network wildcard throws ObsPy TypeError

### ISSUE THREAD

**Issue by bch0w** [adjtomo/pysep#33]
@ammcpherson  identified that when running the attached config file, which features a `*` wildcard for networks, we are hit with a TypeError coming from ObsPy's read_inventory. Potentially this is coming upstream from IRIS returned data but more investigation will be required. If that is the case, we may want to throw a warning or a system exit to keep this from crashing PySEP unexpectedly. 

Note that the config file has been attached as .txt so that GitHub will play nice, but it will need to be renamed as a .yaml file for PySEP to use it.

```python
(pysep) bchow@tern [amanda_pysep_issue] $ pysep -c pysep_config.yaml 
[2022-09-15 16:27:24] - pysep - INFO: overwriting default parameters with config file: 'pysep_config.yaml'
[2022-09-15 16:27:24] - pysep - WARNING: `networks`=='*' will search ALL networks, which may take a long time depending on data availability
[2022-09-15 16:27:25] - pysep - INFO: creating event metadata with user parameters
[2022-09-15 16:27:25] - pysep - INFO: event info summary - origin time: 2022-09-13T23:41:29.004000Z; lat=64.17; lon=-148.51; depth[km]=13.20; magnitude=4.00
[2022-09-15 16:27:25] - pysep - INFO: event tag is: 2022-09-13T234129_CENTRAL_ALASKA
[2022-09-15 16:27:25] - pysep - INFO: querying IRIS for station metadata
Traceback (most recent call last):
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/util/base.py", line 623, in _generic_reader
    generic = callback_func(pathname_or_url, **kwargs)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/util/decorator.py", line 142, in uncompress_file
    return func(filename, *args, **kwargs)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/inventory/inventory.py", line 100, in _read
    inventory, format = _read_from_plugin('inventory', filename, format=format,
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/util/base.py", line 402, in _read_from_plugin
    raise TypeError('Unknown format for file %s' % filename)
TypeError: Unknown format for file <_io.BytesIO object at 0x7f8f25bdaac0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bchow/miniconda3/envs/pysep/bin/pysep", line 33, in <module>
    sys.exit(load_entry_point('pysep', 'console_scripts', 'pysep')())
  File "/home/bchow/REPOSITORIES/pysep/pysep/pysep.py", line 1410, in main
    sep.run()
  File "/home/bchow/REPOSITORIES/pysep/pysep/pysep.py", line 1168, in run
    self.inv = self.get_stations()
  File "/home/bchow/REPOSITORIES/pysep/pysep/pysep.py", line 620, in get_stations
    inv = self.c.get_stations(
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/clients/fdsn/client.py", line 753, in get_stations
    inventory = read_inventory(data_stream)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/util/decorator.py", line 291, in _map_example_filename
    return func(*args, **kwargs)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/inventory/inventory.py", line 91, in read_inventory
    return _generic_reader(path_or_file_object, _read, format=format,
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/util/base.py", line 630, in _generic_reader
    generic = callback_func(fh.name, **kwargs)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/util/decorator.py", line 202, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/inventory/inventory.py", line 100, in _read
    inventory, format = _read_from_plugin('inventory', filename, format=format,
  File "/home/bchow/miniconda3/envs/pysep/lib/python3.10/site-packages/obspy/core/util/base.py", line 402, in _read_from_plugin
    raise TypeError('Unknown format for file %s' % filename)
TypeError: Unknown format for file /tmp/obspy-y4axy6z3.tmp

```
[pysep_config.txt](https://github.com/uafgeotools/pysep/files/9579728/pysep_config.txt)

**Comment by bch0w** [comment]
Strangely I just tried this again on my personal Linux machine and did **not** get this TypeError. 

```python-traceback
(pysep) [bchow@blackbox wildcard_error]$ pysep -c pysep_config.yaml
[2022-10-14 11:32:41] - pysep - INFO: overwriting default parameters with config file: 'pysep_config.yaml'
[2022-10-14 11:32:41] - pysep - WARNING: `networks`=='*' will search ALL networks, which may take a long time depending on data availability
[2022-10-14 11:32:42] - pysep - INFO: creating event metadata with user parameters
[2022-10-14 11:32:42] - pysep - INFO: event info summary - origin time: 2022-09-13T23:41:29.004000Z; lat=64.17; lon=-148.51; depth[km]=13.20; magnitude=4.00
[2022-10-14 11:32:42] - pysep - INFO: event tag is: 2022-09-13T234129_CENTRAL_ALASKA
[2022-10-14 11:32:42] - pysep - INFO: querying IRIS for station metadata
[2022-10-14 11:33:49] - pysep - INFO: collected 7600 channels from 2412 stations in 127 networks from IRIS
[2022-10-14 11:34:05] - pysep - INFO: 2355 traces outside distance bounds [0, 300.0]km
[2022-10-14 11:34:25] - pysep - INFO: 0 traces outside azimuth bounds [0, 360]deg
[2022-10-14 11:34:26] - pysep - INFO: querying client 'IRIS' for waveforms
[2022-10-14 11:34:26] - pysep - INFO: querying 57 lines in bulk client request...
```

I KeyboardInteruppted the task to avoid downloading these waveforms but this will require more investigation on my workstation. For reference my Conda environment is running ObsPy 1.3.0

**Comment by bch0w** [comment]
I am no longer able to reproduce this error. 

I just tested this again a fresh PySEP conda environment (ObsPy==1.4.0) and was able to successfully gather data for a '*' wildcard network entry (using the `pysep_config` from the original posting). Perhaps this was a bug in a previous version of ObsPy?

I will close this issue but @ammcpherson if you run into this issue again could you please comment or open a new issue?
